BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[AUDITORIUM] (
    [AUDITORIUM] CHAR(20) NOT NULL,
    [AUDITORIUM_TYPE] CHAR(10),
    [AUDITORIUM_CAPACITY] INT CONSTRAINT [AUDITORIUM_CAPACITY_CHECK] DEFAULT 1,
    [AUDITORIUM_NAME] VARCHAR(50),
    CONSTRAINT [AUDITORIUM_PK] PRIMARY KEY CLUSTERED ([AUDITORIUM])
);

-- CreateTable
CREATE TABLE [dbo].[AUDITORIUM_TYPE] (
    [AUDITORIUM_TYPE] CHAR(10) NOT NULL,
    [AUDITORIUM_TYPENAME] VARCHAR(30),
    CONSTRAINT [AUDITORIUM_TYPE_PK] PRIMARY KEY CLUSTERED ([AUDITORIUM_TYPE])
);

-- CreateTable
CREATE TABLE [dbo].[FACULTY] (
    [FACULTY] CHAR(10) NOT NULL,
    [FACULTY_NAME] VARCHAR(50) CONSTRAINT [DF__FACULTY__FACULTY__24927208] DEFAULT '???',
    CONSTRAINT [PK__FACULTY__81E78829DD46B8E9] PRIMARY KEY CLUSTERED ([FACULTY])
);

-- CreateTable
CREATE TABLE [dbo].[PULPIT] (
    [PULPIT] CHAR(20) NOT NULL,
    [PULPIT_NAME] VARCHAR(100),
    [FACULTY] CHAR(10),
    CONSTRAINT [PULPIT_PK] PRIMARY KEY CLUSTERED ([PULPIT])
);

-- CreateTable
CREATE TABLE [dbo].[SUBJECT] (
    [SUBJECT] CHAR(10) NOT NULL,
    [SUBJECT_NAME] VARCHAR(100),
    [PULPIT] CHAR(20),
    CONSTRAINT [SUBJECT_PK] PRIMARY KEY CLUSTERED ([SUBJECT]),
    CONSTRAINT [UQ__SUBJECT__29B3CFA76684FF4B] UNIQUE NONCLUSTERED ([SUBJECT_NAME])
);

-- CreateTable
CREATE TABLE [dbo].[sysdiagrams] (
    [name] NVARCHAR(128) NOT NULL,
    [principal_id] INT NOT NULL,
    [diagram_id] INT NOT NULL IDENTITY(1,1),
    [version] INT,
    [definition] VARBINARY(max),
    CONSTRAINT [PK__sysdiagr__C2B05B61C3230B2C] PRIMARY KEY CLUSTERED ([diagram_id]),
    CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED ([principal_id],[name])
);

-- CreateTable
CREATE TABLE [dbo].[TEACHER] (
    [TEACHER] CHAR(10) NOT NULL,
    [TEACHER_NAME] VARCHAR(100),
    [PULPIT] CHAR(20),
    CONSTRAINT [TEACHER_PK] PRIMARY KEY CLUSTERED ([TEACHER])
);

-- AddForeignKey
ALTER TABLE [dbo].[AUDITORIUM] ADD CONSTRAINT [AUDITORIUM_AUDITORIUM_TYPE_FK] FOREIGN KEY ([AUDITORIUM_TYPE]) REFERENCES [dbo].[AUDITORIUM_TYPE]([AUDITORIUM_TYPE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[PULPIT] ADD CONSTRAINT [PULPIT_FACULTY_FK] FOREIGN KEY ([FACULTY]) REFERENCES [dbo].[FACULTY]([FACULTY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SUBJECT] ADD CONSTRAINT [SUBJECT_PULPIT_FK] FOREIGN KEY ([PULPIT]) REFERENCES [dbo].[PULPIT]([PULPIT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TEACHER] ADD CONSTRAINT [TEACHER_PULPIT_FK] FOREIGN KEY ([PULPIT]) REFERENCES [dbo].[PULPIT]([PULPIT]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
